<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="3" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-22T12:19:32 CLT" name="Surefire suite" finished-at="2025-05-22T12:23:44 CLT" duration-ms="252072">
    <groups>
      <group name="regression">
        <method signature="AgriTest.inicioSesionAgriTest()[pri:0, instance:principal.AgriTest@c446b14]" name="inicioSesionAgriTest" class="principal.AgriTest"/>
        <method signature="NavegacionTest.abrirMenuTest()[pri:0, instance:principal.NavegacionTest@614aeccc]" name="abrirMenuTest" class="principal.NavegacionTest"/>
        <method signature="NavegacionTest.facturaElectronicaSiiAgriTest()[pri:0, instance:principal.NavegacionTest@614aeccc]" name="facturaElectronicaSiiAgriTest" class="principal.NavegacionTest"/>
        <method signature="NavegacionTest.inicioSesionAgriTest()[pri:0, instance:principal.NavegacionTest@614aeccc]" name="inicioSesionAgriTest" class="principal.NavegacionTest"/>
        <method signature="NavegacionTest.notaCreditoSiiAgriTest()[pri:0, instance:principal.NavegacionTest@614aeccc]" name="notaCreditoSiiAgriTest" class="principal.NavegacionTest"/>
        <method signature="NavegacionTest.notaDebitoSiiAgriTest()[pri:0, instance:principal.NavegacionTest@614aeccc]" name="notaDebitoSiiAgriTest" class="principal.NavegacionTest"/>
        <method signature="NavegacionTest.remuneracionSiiAgriTest()[pri:0, instance:principal.NavegacionTest@614aeccc]" name="remuneracionSiiAgriTest" class="principal.NavegacionTest"/>
      </group> <!-- regression -->
    </groups>
    <test started-at="2025-05-22T12:19:32 CLT" name="Surefire test" finished-at="2025-05-22T12:23:44 CLT" duration-ms="252072">
      <class name="principal.NavegacionTest">
        <test-method is-config="true" signature="masterSetUp()[pri:0, instance:principal.NavegacionTest@614aeccc]" started-at="2025-05-22T12:19:50 CLT" name="masterSetUp" finished-at="2025-05-22T12:19:51 CLT" duration-ms="1034" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- masterSetUp -->
        <test-method signature="abrirMenuTest()[pri:0, instance:principal.NavegacionTest@614aeccc]" started-at="2025-05-22T12:19:51 CLT" name="abrirMenuTest" finished-at="2025-05-22T12:20:09 CLT" duration-ms="18553" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- abrirMenuTest -->
        <test-method is-config="true" signature="masterTearDown()[pri:0, instance:principal.NavegacionTest@614aeccc]" started-at="2025-05-22T12:20:10 CLT" name="masterTearDown" finished-at="2025-05-22T12:20:10 CLT" duration-ms="119" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- masterTearDown -->
        <test-method is-config="true" signature="masterSetUp()[pri:0, instance:principal.NavegacionTest@614aeccc]" started-at="2025-05-22T12:20:10 CLT" name="masterSetUp" finished-at="2025-05-22T12:20:11 CLT" duration-ms="984" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- masterSetUp -->
        <test-method signature="facturaElectronicaSiiAgriTest()[pri:0, instance:principal.NavegacionTest@614aeccc]" started-at="2025-05-22T12:20:11 CLT" name="facturaElectronicaSiiAgriTest" finished-at="2025-05-22T12:21:01 CLT" duration-ms="50055" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at principal.NavegacionTest.facturaElectronicaSiiAgriTest(NavegacionTest.java:176)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- facturaElectronicaSiiAgriTest -->
        <test-method is-config="true" signature="masterTearDown()[pri:0, instance:principal.NavegacionTest@614aeccc]" started-at="2025-05-22T12:21:01 CLT" name="masterTearDown" finished-at="2025-05-22T12:21:02 CLT" duration-ms="172" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- masterTearDown -->
        <test-method is-config="true" signature="masterSetUp()[pri:0, instance:principal.NavegacionTest@614aeccc]" started-at="2025-05-22T12:21:02 CLT" name="masterSetUp" finished-at="2025-05-22T12:21:03 CLT" duration-ms="1080" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- masterSetUp -->
        <test-method signature="inicioSesionAgriTest()[pri:0, instance:principal.NavegacionTest@614aeccc]" started-at="2025-05-22T12:21:03 CLT" name="inicioSesionAgriTest" finished-at="2025-05-22T12:21:16 CLT" duration-ms="13037" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inicioSesionAgriTest -->
        <test-method is-config="true" signature="masterTearDown()[pri:0, instance:principal.NavegacionTest@614aeccc]" started-at="2025-05-22T12:21:16 CLT" name="masterTearDown" finished-at="2025-05-22T12:21:16 CLT" duration-ms="95" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- masterTearDown -->
        <test-method is-config="true" signature="masterSetUp()[pri:0, instance:principal.NavegacionTest@614aeccc]" started-at="2025-05-22T12:21:16 CLT" name="masterSetUp" finished-at="2025-05-22T12:21:17 CLT" duration-ms="1038" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- masterSetUp -->
        <test-method signature="notaCreditoSiiAgriTest()[pri:0, instance:principal.NavegacionTest@614aeccc]" started-at="2025-05-22T12:21:17 CLT" name="notaCreditoSiiAgriTest" finished-at="2025-05-22T12:22:09 CLT" duration-ms="51952" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at principal.NavegacionTest.notaCreditoSiiAgriTest(NavegacionTest.java:280)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- notaCreditoSiiAgriTest -->
        <test-method is-config="true" signature="masterTearDown()[pri:0, instance:principal.NavegacionTest@614aeccc]" started-at="2025-05-22T12:22:09 CLT" name="masterTearDown" finished-at="2025-05-22T12:22:09 CLT" duration-ms="98" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- masterTearDown -->
        <test-method is-config="true" signature="masterSetUp()[pri:0, instance:principal.NavegacionTest@614aeccc]" started-at="2025-05-22T12:22:09 CLT" name="masterSetUp" finished-at="2025-05-22T12:22:10 CLT" duration-ms="1020" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- masterSetUp -->
        <test-method signature="notaDebitoSiiAgriTest()[pri:0, instance:principal.NavegacionTest@614aeccc]" started-at="2025-05-22T12:22:10 CLT" name="notaDebitoSiiAgriTest" finished-at="2025-05-22T12:23:00 CLT" duration-ms="49820" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at principal.NavegacionTest.notaDebitoSiiAgriTest(NavegacionTest.java:384)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- notaDebitoSiiAgriTest -->
        <test-method is-config="true" signature="masterTearDown()[pri:0, instance:principal.NavegacionTest@614aeccc]" started-at="2025-05-22T12:23:00 CLT" name="masterTearDown" finished-at="2025-05-22T12:23:01 CLT" duration-ms="103" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- masterTearDown -->
        <test-method is-config="true" signature="masterSetUp()[pri:0, instance:principal.NavegacionTest@614aeccc]" started-at="2025-05-22T12:23:01 CLT" name="masterSetUp" finished-at="2025-05-22T12:23:02 CLT" duration-ms="1001" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- masterSetUp -->
        <test-method signature="remuneracionSiiAgriTest()[pri:0, instance:principal.NavegacionTest@614aeccc]" started-at="2025-05-22T12:23:02 CLT" name="remuneracionSiiAgriTest" finished-at="2025-05-22T12:23:44 CLT" duration-ms="42267" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sutil] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sutil] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at principal.NavegacionTest.remuneracionSiiAgriTest(NavegacionTest.java:477)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- remuneracionSiiAgriTest -->
        <test-method is-config="true" signature="masterTearDown()[pri:0, instance:principal.NavegacionTest@614aeccc]" started-at="2025-05-22T12:23:44 CLT" name="masterTearDown" finished-at="2025-05-22T12:23:44 CLT" duration-ms="104" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- masterTearDown -->
      </class> <!-- principal.NavegacionTest -->
      <class name="principal.AgriTest">
        <test-method is-config="true" signature="masterSetUp()[pri:0, instance:principal.AgriTest@c446b14]" started-at="2025-05-22T12:19:32 CLT" name="masterSetUp" finished-at="2025-05-22T12:19:36 CLT" duration-ms="3302" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- masterSetUp -->
        <test-method signature="inicioSesionAgriTest()[pri:0, instance:principal.AgriTest@c446b14]" started-at="2025-05-22T12:19:36 CLT" name="inicioSesionAgriTest" finished-at="2025-05-22T12:19:49 CLT" duration-ms="13686" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inicioSesionAgriTest -->
        <test-method is-config="true" signature="masterTearDown()[pri:0, instance:principal.AgriTest@c446b14]" started-at="2025-05-22T12:19:50 CLT" name="masterTearDown" finished-at="2025-05-22T12:19:50 CLT" duration-ms="135" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- masterTearDown -->
      </class> <!-- principal.AgriTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
